<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <RimWorldManaged Condition="'$(RimWorldManaged)' == ''">/mnt/c/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin64_Data/Managed</RimWorldManaged>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ApiChecks.cs" />
    <Reference Include="RimArt"><HintPath>../../../1.6/Assemblies/RimArt.dll</HintPath></Reference>
    <Reference Include="Assembly-CSharp"><HintPath>$(RimWorldManaged)/Assembly-CSharp.dll</HintPath></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(RimWorldManaged)/UnityEngine.CoreModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>$(RimWorldManaged)/UnityEngine.IMGUIModule.dll</HintPath></Reference>
    <Reference Include="0Harmony"><HintPath>$(NuGetPackageRoot)lib.harmony/2.3.3/lib/net48/0Harmony.dll</HintPath></Reference>
  </ItemGroup>
</Project>
